project_name: memo

before:
  hooks:
    - go mod tidy

builds:
  - id: memo-cache
    main: ./cmd/cache-builder
    binary: cache-builder
    goos: [linux, darwin]
    goarch: [amd64, arm64]

archives:
  - id: archive
    format: tar.gz
    builds:
      - cache-builder
    files:
      - memo.sh
    name_template: "memo_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: ldonnez
    name: memo
